-- MySQL Script generated by MySQL Workbench
-- Mon Aug 12 20:11:47 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdnexoempleo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdnexoempleo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdnexoempleo` DEFAULT CHARACTER SET utf8 ;
USE `bdnexoempleo` ;

-- -----------------------------------------------------
-- Table `bdnexoempleo`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `apellido1` VARCHAR(50) NOT NULL,
  `apellido2` VARCHAR(50) NULL DEFAULT NULL,
  `ci` VARCHAR(50) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(50) NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `foto_validacion` VARCHAR(100) NOT NULL,
  `validacion` TINYINT NOT NULL,
  `rol` VARCHAR(50) NOT NULL,
  `telf_celular` INT NOT NULL,
  `descripcion` VARCHAR(80) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1 COMMENT '0 Inactivo/Dado de baja/eliminacion logica\n1 Activo',
  `fecha_creacion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecha_ultimaActualizacion` TIMESTAMP NULL DEFAULT NULL,
  `idusuario_mod` SMALLINT NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`categorias` (
  `idcategorias` INT NOT NULL AUTO_INCREMENT,
  `nombre_catg` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`empleadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`empleadores` (
  `idempleadores` INT NOT NULL AUTO_INCREMENT,
  `tipo_empleador` INT NOT NULL,
  `nit` INT NOT NULL,
  `razon_social` VARCHAR(100) NOT NULL,
  `validacion` TINYINT NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idempleadores`),
  INDEX `fk_empleadores_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  INDEX `fk_empleadores_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_empleadores_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bdnexoempleo`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleadores_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `bdnexoempleo`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`administrativos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`administrativos` (
  `idadministrativos` INT NOT NULL AUTO_INCREMENT,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idadministrativos`),
  INDEX `fk_administrativos_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_administrativos_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bdnexoempleo`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`Especialidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`Especialidades` (
  `idEspecialidades` INT NOT NULL AUTO_INCREMENT,
  `nombre_espec` VARCHAR(80) NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idEspecialidades`),
  INDEX `fk_Especialidades_categorias1_idx` (`categorias_idcategorias` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidades_categorias1`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `bdnexoempleo`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`trabajadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`trabajadores` (
  `idtrabajadores` INT NOT NULL AUTO_INCREMENT,
  `sueldo_aspirado` INT UNSIGNED NOT NULL,
  `anos_experiencia` INT UNSIGNED NOT NULL,
  `nivel_estudio` VARCHAR(100) NOT NULL,
  `disponibilidad_viaje` TINYINT NOT NULL,
  `disponibilidad_mudanza` TINYINT NOT NULL,
  `cur_vit` VARCHAR(100) NOT NULL,
  `usuario_idusuario` INT NOT NULL,
  PRIMARY KEY (`idtrabajadores`),
  INDEX `fk_trabajadores_usuario1_idx` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_trabajadores_usuario1`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `bdnexoempleo`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`esp_trab`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`esp_trab` (
  `Especialidades_idEspecialidades` INT NOT NULL,
  `trabajadores_idtrabajadores` INT NOT NULL,
  PRIMARY KEY (`Especialidades_idEspecialidades`, `trabajadores_idtrabajadores`),
  INDEX `fk_esp_trab_trabajadores1_idx` (`trabajadores_idtrabajadores` ASC) VISIBLE,
  CONSTRAINT `fk_esp_trab_Especialidades1`
    FOREIGN KEY (`Especialidades_idEspecialidades`)
    REFERENCES `bdnexoempleo`.`Especialidades` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_esp_trab_trabajadores1`
    FOREIGN KEY (`trabajadores_idtrabajadores`)
    REFERENCES `bdnexoempleo`.`trabajadores` (`idtrabajadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`ofertas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`ofertas` (
  `idofertas` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(200) NOT NULL,
  `cant_vacantes` INT UNSIGNED NOT NULL,
  `sueldo` INT UNSIGNED NOT NULL,
  `nivel_estudio_requerido` VARCHAR(100) NOT NULL,
  `anos_experiencia_requerido` INT UNSIGNED NOT NULL,
  `disponibilidad_viaje` TINYINT NOT NULL,
  `disponibilidad_mudanza` TINYINT NOT NULL,
  `estado` TINYINT NOT NULL,
  `fecha_creacion` DATE NOT NULL,
  `idusuario_mod` VARCHAR(45) NOT NULL,
  `empleadores_idempleadores` INT NOT NULL,
  PRIMARY KEY (`idofertas`),
  INDEX `fk_ofertas_empleadores1_idx` (`empleadores_idempleadores` ASC) VISIBLE,
  CONSTRAINT `fk_ofertas_empleadores1`
    FOREIGN KEY (`empleadores_idempleadores`)
    REFERENCES `bdnexoempleo`.`empleadores` (`idempleadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`solicitudes` (
  `idSolicitudes` INT NOT NULL,
  `fecha_solicitud` DATE NOT NULL,
  `estado_aceptacion` TINYINT NOT NULL DEFAULT 0,
  `trabajadores_idtrabajadores` INT NOT NULL,
  `ofertas_idofertas` INT NOT NULL,
  PRIMARY KEY (`idSolicitudes`),
  INDEX `fk_solicitudes_trabajadores1_idx` (`trabajadores_idtrabajadores` ASC) VISIBLE,
  INDEX `fk_solicitudes_ofertas1_idx` (`ofertas_idofertas` ASC) VISIBLE,
  CONSTRAINT `fk_solicitudes_trabajadores1`
    FOREIGN KEY (`trabajadores_idtrabajadores`)
    REFERENCES `bdnexoempleo`.`trabajadores` (`idtrabajadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitudes_ofertas1`
    FOREIGN KEY (`ofertas_idofertas`)
    REFERENCES `bdnexoempleo`.`ofertas` (`idofertas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`mensaje` (
  `idMensaje` INT NOT NULL AUTO_INCREMENT,
  `fecha` VARCHAR(45) NOT NULL,
  `contenido` VARCHAR(10000) NULL,
  `empleadores_idempleadores` INT NOT NULL,
  `solicitudes_idSolicitudes` INT NOT NULL,
  PRIMARY KEY (`idMensaje`),
  INDEX `fk_mensaje_empleadores1_idx` (`empleadores_idempleadores` ASC) VISIBLE,
  INDEX `fk_mensaje_solicitudes1_idx` (`solicitudes_idSolicitudes` ASC) VISIBLE,
  CONSTRAINT `fk_mensaje_empleadores1`
    FOREIGN KEY (`empleadores_idempleadores`)
    REFERENCES `bdnexoempleo`.`empleadores` (`idempleadores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mensaje_solicitudes1`
    FOREIGN KEY (`solicitudes_idSolicitudes`)
    REFERENCES `bdnexoempleo`.`solicitudes` (`idSolicitudes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`habilidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`habilidades` (
  `idhabilidades` INT NOT NULL,
  `nombre` VARCHAR(80) NULL,
  PRIMARY KEY (`idhabilidades`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdnexoempleo`.`habil_esp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdnexoempleo`.`habil_esp` (
  `Especialidades_idEspecialidades` INT NOT NULL,
  `habilidades_idhabilidades` INT NOT NULL,
  INDEX `fk_habil_esp_Especialidades1_idx` (`Especialidades_idEspecialidades` ASC) VISIBLE,
  INDEX `fk_habil_esp_habilidades1_idx` (`habilidades_idhabilidades` ASC) VISIBLE,
  CONSTRAINT `fk_habil_esp_Especialidades1`
    FOREIGN KEY (`Especialidades_idEspecialidades`)
    REFERENCES `bdnexoempleo`.`Especialidades` (`idEspecialidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_habil_esp_habilidades1`
    FOREIGN KEY (`habilidades_idhabilidades`)
    REFERENCES `bdnexoempleo`.`habilidades` (`idhabilidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
